NoterbRails/config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/notes/export_all', to: 'notes#export_all', as: 'export_all_notes'

  devise_for :users
  resources :notes
  resources :books

  resources :notes do
    member do
      get 'export'
    end
  end
  resources :books do
    member do
      get 'export'
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

NoterbRails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

NoterbRails/app/models/book.rb
require 'rubygems'
require 'zip'

class Book < ApplicationRecord
  has_many :notes, dependent: :destroy
  belongs_to :user, foreign_key: 'user_id'
  validates :name, presence: true

  def to_s
    name
  end

  def global?
    name == 'Global'
  end

  def export_as_zip
    compiled_file = Zip::OutputStream.write_buffer do |zip_file|
      self.notes.each do |note|
        zip_file.put_next_entry("#{note.title}.html")
        zip_file << note.export_html
      end
    end
    compiled_file.rewind
    data = compiled_file.sysread
  end

end

NoterbRails/app/models/note.rb
class Note < ApplicationRecord
  belongs_to :book, foreign_key: 'book_id', optional: true
  belongs_to :user, foreign_key: 'user_id'

  validates :title, presence: true


  def export_html
    text = "#{self.title} <br> #{self.content}"
    md=Redcarpet::Markdown.new(Redcarpet::Render::HTML,tables: true)
    data = md.render(text)
    # File.open("note_#{title}.html", 'w') { |file| file.write md }
    return data
  end

  def export_as_file
    File.open("note_#{title}.html", 'w') { |file| file.write self.export_html }
  end
end

NoterbRails/app/models/user.rb
class User < ApplicationRecord

  has_many :books, dependent: :destroy, inverse_of: :user
  has_many :notes, dependent: :destroy, inverse_of: :user

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :create_global

  def create_global
    self.books.create(name: 'Global')
  end

  def export_data_zip
    compiled_file = Zip::OutputStream.write_buffer do |zip_file|
      self.books.each do |book|
        zip_file.put_next_entry("#{book.name}.zip")
        zip_file << book.export_as_zip
      end
    end
    compiled_file.rewind
    data = compiled_file.sysread
  end
end

NoterbRails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

NoterbRails/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = current_user.books
  end

  # GET /books/1 or /books/1.json
  def show
    if current_user.id != @book.user_id
      redirect_to books_url, notice: "The book you are trying to access is not yours, don't spy on other people books :P"
    end
    @notes = @book.notes
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)
    @book.user = User.find(current_user.id)
    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    if @book.global?
      @book.notes.destroy_all
      respond_to do |format|
        format.html { redirect_to books_url, notice: "Global notes have been successfully destroyed." }
        format.json { head :no_content }
      end
    else
      @book.destroy
      respond_to do |format|
        format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  end

  def export
    @book = Book.find(params[:id])
    respond_to do |format|
      format.html { send_data @book.export_as_zip, filename: "book_#{@book.name}.zip", notice: "Book was successfully exported." }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:name)
    end
end

NoterbRails/app/controllers/home_controller.rb
class HomeController < ApplicationController
  # include Devise::Controllers::Helpers
  def index
    @user = current_user
  end
end

NoterbRails/app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[ show edit update destroy ]


  # GET /notes or /notes.json
  def index
    @notes = current_user.notes
  end

  # GET /notes/1 or /notes/1.json
  def show
    if current_user.id != @note.user_id
      redirect_to books_url, notice: "The note you are trying to access is not yours, don't spy on other people notes :P"
    end
  end

  # GET /notes/new
  def new
    @note = current_user.notes.build
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes or /notes.json
  def create
    puts note_params
    @note = Note.new(note_params.merge(user_id: current_user.id))
    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
      # format.json { head :no_content }
    end
  end

  def export
    @note = Note.find(params[:id])
    respond_to do |format|
      format.html { send_data @note.export_html, filename: "note_#{@note.title}.html", notice: "Note was successfully exported." }
      # format.json { head :no_content }
    end
  end

  def export_all
    respond_to do |format|
      format.html { send_data current_user.export_data_zip, filename: "all_notes.zip", notice: "All notes have been exported." }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:title, :content, :book_id)
    end
end

NoterbRails/app/helpers/application_helper.rb
module ApplicationHelper
end

NoterbRails/app/helpers/books_helper.rb
module BooksHelper
end

NoterbRails/app/helpers/home_helper.rb
module HomeHelper
end

NoterbRails/app/helpers/notes_helper.rb
module NotesHelper
end

NoterbRails/app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

NoterbRails/app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

NoterbRails/app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table class="table table-striped table-hover table-bordered table-responsive">
  <thead>
    <tr>
      <th>Name</th>
      <th>#Notes</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td><%= book.notes.count %></td>
        <td><%= link_to 'Show', book %></td>
        <% if !book.global? %>
          <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <% else %>
          <td> </td>
        <% end %>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Export', export_book_path(book)%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

NoterbRails/app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

NoterbRails/app/views/books/show.html.erb
<p id="notice" class="alert alert-dark"><%= notice %></p>
<h1>
  <strong>Book name:</strong>
  <%= @book.name %>
</h1>

<% if @notes.count == 0 %>
  <h3> This book has no notes.</h3>
<% else %>
  <h3>Notes</h3>

  <table class="table table-striped table-hover table-bordered table-responsive">
    <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><div class = "content-td"><%= link_to note.title, note_path(note) %></div></td>
        <td><div class = "content-td"><%= note.content %></div></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

<% end %>

<% if !@book.global? %>
  <%= link_to 'Edit', edit_book_path(@book) %> |
<% end %>
<%= link_to 'New Note', new_note_path %>
<%= link_to 'Back', books_path %>

NoterbRails/app/views/home/index.html.erb
<div>
  <h1>
  Welcome!
  </h1>
  <%= link_to "Books", books_path, :class=>"btn btn-light home-btns" %>
  <%= link_to "Notes", notes_path, :class=>"btn btn-light home-btns" %>
</div>

NoterbRails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Noterb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
    <div class="container-fluid ">
      <h1 class="navbar-brand" >Noterb</h1>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0 d-flex flex-row bd-highlight">
          <li class="nav-item">
            <%= link_to 'HOME', root_path ,:class=>"nav-link active" %>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "#{current_user.username}", edit_user_registration_path,:class=>"nav-link active" %>
            </li>
            <li class="nav-item">
              <%= link_to "Log Out", destroy_user_session_path, method: :delete,:class=>"nav-link active" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Log In", new_user_session_path ,:class=>"nav-link active"%>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class="general-container">
    <%= yield %>
  </div>
  </body>
</html>

NoterbRails/app/views/notes/_form.html.erb
<%= form_with(model: note) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :book_id %>
    <%= form.collection_select :book_id, current_user.books.order(:name), :id, :name,  {class: "form-control"} %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

NoterbRails/app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

NoterbRails/app/views/notes/export.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @note.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @note.content %>
</p>

<p>
  <strong>Book:</strong>
  <%= link_to @note.book, book_path(@note.book) %>
</p>

<%= link_to 'Back', notes_path %>

NoterbRails/app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notes</h1>
<% if @notes.count == 0 %>
  <h3> There are no notes to display.</h3>
<% else %>
  <table class="table table-striped table-hover table-bordered table-responsive">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Book</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><div class = "content-td"><%= note.title %></div></td>
        <td><div class = "content-td"><%= note.content %></div></td>
        <td>
          <%= link_to note.book, book_path(note.book) %>
        </td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Export', export_note_path(note)%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<br>

<%= link_to 'New Note', new_note_path %>
<%= link_to 'Export All', export_all_notes_path %>

NoterbRails/app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Back', notes_path %>

NoterbRails/app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @note.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @note.content %>
</p>

<p>
  <strong>Book:</strong>
  <%= link_to @note.book, book_path(@note.book) %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>